name: CameraObscura
main: fromgate.obscura.Obscura
version: 0.1.2
author: fromgate, fromgate@gmail.com
load: POSTWORLD
commands:
   photo:
      aliases: [camera,obscura,co]
      description: 
      usage: 
           /photo help
          