name: CameraObscura
main: me.fromgate.obscura.Obscura
version: 0.2.5
author: fromgate, fromgate@gmail.com
load: POSTWORLD
commands:
   photo:
      aliases: [camera,obscura,co]
      description: 
      usage: 
           /photo help